version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pastebin-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=/app/data/pastes.db
      - JWT_SECRET=${JWT_SECRET:-change-this-secret-in-production}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
      - MAX_PASTE_SIZE=${MAX_PASTE_SIZE:-1048576}
      - MAX_PASTES_PER_IP=${MAX_PASTES_PER_IP:-10}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-15}
      - ALLOWED_ORIGINS=https://pastebin.bruhphoria.xyz
    volumes:
      - pastebin_data:/app/data
      - backend_logs:/var/log
    networks:
      - pastebin_network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=64M
      - /var/cache:noexec,nosuid,size=32M
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://api.pastebin.bruhphoria.xyz
    container_name: pastebin-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - pastebin_network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - DAC_OVERRIDE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=32M
      - /var/cache/nginx:noexec,nosuid,size=64M
      - /var/run:noexec,nosuid,size=16M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pastebin_data:
    driver: local
  backend_logs:
    driver: local

networks:
  pastebin_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
